
#ifndef TARGET_VERSION_H
#define TARGET_VERSION_H

// 内部版本
const int TARGET_INTERNAL_MAJOR_VERSION = 1;
const int TARGET_INTERNAL_MINOR_VERSION = 0;
const int TARGET_INTERNAL_PATCH_VERSION = 0;

// 产品版本
const int TARGET_MAJOR_VERSION = 1;
const int TARGET_MINOR_VERSION = 0;
const int TARGET_PATCH_VERSION = 0;

#endif	// TARGET_VERSION_H
